---
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
  - darwin
  - linux
registries:
- type: standard
  ref: v4.467.0 # renovate: depName=aquaproj/aqua-registry
- name: local
  type: local
  path: aqua-registry.yaml
packages:
- name: hashicorp/terraform@v1.14.1
- name: rhysd/actionlint@v1.7.10
- name: suzuki-shunsuke/pinact@v3.7.4
- name: fujiwara/iam-policy-finder@v0.0.4
- name: koalaman/shellcheck@v0.11.0
- name: suzuki-shunsuke/ghatm@v1.0.0
- name: cli/cli@v2.86.0
- name: jqlang/jq@jq-1.8.1
- name: peco/peco@v0.5.11
- name: mikefarah/yq@v4.45.3
- name: direnv/direnv@v2.37.1
- name: x-motemen/ghq@v1.8.1
- name: itkq/whichpr@v0.0.1
  registry: local
- name: goreleaser/goreleaser@v2.13.3
- name: golang/go@go1.26.0
- name: a8m/envsubst@v1.4.3
- name: suzuki-shunsuke/ghcp@v1.16.0
- name: sharkdp/bat@v0.26.1
- name: neovim/neovim@v0.11.6
- name: abiosoft/colima@v0.10.0
- name: lima-vm/lima@v2.0.3
- name: docker/cli@v29.1.4
- name: aws/aws-cli@2.33.22
- name: awslabs/amazon-ecr-credential-helper@v0.11.0
- name: oven-sh/bun@bun-v1.3.9
